[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.29.0"

[programs.localnet]
compazz_funds = "CompazzFhXk57gk7TPQBnREn5X24q626eJjWdevnet11111"

[programs.devnet]
compazz_funds = "CompazzFhXk57gk7TPQBnREn5X24q626eJjWdevnet11111"

[programs.mainnet]
compazz_funds = "CompazzFhXk57gk7TPQBnREn5X24q626eJjWdevnet11111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"