[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
compazz_funds = "3tcEee5UQfuis8tApyMfcyhkCfjLwb39nVrEVUo82bWJ"

[programs.devnet]
compazz_funds = "3tcEee5UQfuis8tApyMfcyhkCfjLwb39nVrEVUo82bWJ"

[programs.mainnet]
compazz_funds = "3tcEee5UQfuis8tApyMfcyhkCfjLwb39nVrEVUo82bWJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"